.zuul.d/jobs.yaml
.zuul.d/project.yaml
tools/check_ansible_builder_changed.sh
tox.ini

Validate we can build ansible/network-ee using ansible-builder.

Add network-ee-tox-ansible-builder job

---

tools/check_ansible_builder_changed.sh

Give more debug info to a user when validation fails.

Add extra info when tox -eansible-builder fails

---

Containerfile

This switch network-ee to use latest code from ansible-builder. Which
includes moving to centos-8 and multi-stage builds.

Changes needed for latest ansible-builder

---

.zuul.d/jobs.yaml

This gets depends-on working with these container images.

Jobs need access to python-builder-container-images

---

.zuul.d/jobs.yaml
tests/Containerfile
tests/bindep.txt
tests/requirements.txt

This will create 3 new test images to be used in our CI. A top-level
test image, then sanity and unit test images.

Create network-ee-test images

---

.zuul.d/jobs.yaml

We incorrectly had sanity not unit.

Fix bug with network-ee-unit-tests target

---

.zuul.d/jobs.yaml

Now all container jobs are using the same nodeset.

Use same nodeset for network-ee-tox-ansible-builder

---

.zuul.d/jobs.yaml
.zuul.d/project.yaml
Containerfile

Bring online the ability to create stable-2.9 images too.
Depends-On: https://github.com/ansible/ansible-builder/pull/167
Depends-On: https://github.com/ansible/network-ee/pull/18

Create network-ee:stable-2.9-latest image

---

.zuul.d/jobs.yaml
Containerfile

We always want to use the latest version of collections publish to
galaxy.
Depends-On: https://github.com/ansible/ansible-builder/pull/173

Use pre-release network collections

---

.zuul.d/jobs.yaml

This allows other projects, to run our jobs.

Setup zuul_work_dir for other jobs to run jobs

---

.zuul.d/jobs.yaml

There is no need to say 'latest', as we always package the latest
stable-2.9 branch.

Rename stable-2.9-latest tag to stable-2.9

---

_build/requirements_combined.txt
tools/execution-environment.yaml
tools/requirements.txt

We currently have a chicken and egg issue with requirements. There is no
way to add a new python dependency, without first releasing a
collection. Which, makes it difficult to properly test, before
releasing.

Add 'ansible.utils' python dependencies

---

.zuul.d/jobs.yaml

Nothing actually uses these images, given we always rebuild them.
Remove them, to simplify things.

Remove job.provides settings

---

.zuul.d/jobs.yaml
.zuul.d/project-templates.yaml
.zuul.d/project.yaml

We'll use these images for testing our network collections.
Depends-On: https://github.com/ansible/ansible-runner/pull/623
Depends-On: https://github.com/ansible/network-ee/pull/36

Add stable-2.10 support for network-ee

---

.zuul.d/jobs.yaml
tests/Containerfile
tests/Containerfile.ansible-test

This should speed things up a fair bit, given we don't have to rebuild
the network-ee-tests image each time for ansible-test CLI commands.

Refactor container build jobs

---

_build/requirements.yml
tools/requirements.yaml

Because we modify the requirements.yaml file in CI, to use pre-merged
network collections. We don't want to download that content from galaxy,
but rather use the collection we build from git.

Revert back to including network collections

---

.zuul.d/project-templates.yaml

As we have more projects merging changes for execution environments
there is more chances for things to break.  Lets put everything into the
same shared queue.

Add network-ee container jobs to integrated queue

---

.zuul.d/project-templates.yaml

Actually, don't force this for now. Until we can get a better handle on
aws testing.
This reverts commit d1786f80a5ac4cf61bc529721515d4e2f04285b1.

Revert "Add network-ee container jobs to integrated queue"

---

.zuul.d/jobs.yaml
.zuul.d/project-templates.yaml

Our registry is only 1vpcu, where our container-build-jobs are 4vcpu.
This should save us some capacity over time.

Run ansible-buildset-registry too

---

.zuul.d/jobs.yaml

This should make our job a little faster, and drop the docker
dependency.

Depend on ansible-buildset-registry for tox build job

---

tests/Containerfile
tests/test-requirements.txt

This is to allow amazon.aws jobs to function.  However, this highlights
the needs of per collection test images / global constraint files.
Something I hopefully will work on shortly.

Add support for local test-requirements.txt file

---

.zuul.d/jobs.yaml
tools/test-setup.sh

This should get us a little closer to RHEL based testing.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1048
Depends-On: https://github.com/ansible/network-ee/pull/107

Switch to centos-8-stream for jobs

---

.zuul.d/project-templates.yaml

When things are busy, we don't want to bring online this node until
we've first build the tarballs.

Add dependency for ansible-buildset-registry

---

.zuul.d/jobs.yaml

Our network-ee-tests images need this image.

Add back python-builder-container-image

---

.zuul.d/integration-jobs.yaml
playbooks/network-ee-integration-tests/pre.yaml
tests/integration/playbooks/site.yaml

By default, we should test with FIPs mode. And collections that don't
want or cannot support it, should set test_fips_mode: false.

Enable FIPS mode for integration testing

---

tests/integration/inventories/ios.yaml
tests/integration/inventories/vyos.yaml

This will be used by cisco.ios network-ee-integration-tests jobs.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1050

Add cisco.ios inventory file

---

test-requirements.txt
tox.ini

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1401
This reverts commit 26604d4836aade226f60f07727776b4eb0c0b092.
pytest 7.1.1 has been released with a fix for the fixture problem.
See: https://github.com/pytest-dev/pytest/issues/9767

Revert "Pin Pytest 6.2.0"

---

tests/integration/playbooks/include_role.yaml
tests/integration/playbooks/site.yaml

Also, use a more explicit string to identify the errors in the logs.
This reverts commit 068ffdd3e99e83d4d39032aeeb67a3bc5b8cddf3.

Revert "don't continue in case of failure"
