ansible/network-ee

.zuul.d/project.yaml

This rebuilds / uploads our image to quay.io every 24 hours. To help
keep it current.

Rebuild our image periodically

---

tests/requirements.txt

Add mising antsibull_changelog dependency

---

.zuul.d/jobs.yaml

Add missing required-projects

---

.zuul.d/jobs.yaml
.zuul.d/project-templates.yaml

This doesn't do what we expected.
Depends-On: https://github.com/ansible/python-builder-image/pull/21

Remove ansible-buildset-registry job

---

.zuul.d/jobs.yaml
tests/Containerfile

This should be more then enough compute to build images now.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/746

Downgrade to ubuntu-bionic-2vpcu nodeset

---

_build/bindep_combined.txt

Refresh bindep files

---

.zuul.d/jobs.yaml
.zuul.d/project-templates.yaml
.zuul.d/project.yaml

Depends-on: https://github.com/ansible/ansible-runner/pull/649
Depends-On: #36

Add network_ee_stable_2.11 jobs

---

_build/bindep_combined.txt
_build/requirements_combined.txt

Refresh _build files

---

tools/cachito/constraints.txt
tools/cachito/setup.cfg

Depends-On: https://github.com/ansible/network-ee/pull/40

Add cachito files

---

tools/cachito/constraints.txt

Add awxkit to cachito constraint

---

tools/cachito/constraints.txt

Add aws requirements to cachito

---

Containerfile

Refresh ansible-builder logic

---

tools/cachito/constraints.txt

Add paramiko to cachito

---

tools/cachito/constraints.txt

Depends-On: https://github.com/ansible/network-ee/pull/49

Remove selectors2 from cachito

---

tools/cachito/build-requirements.txt
tools/cachito/requirements.txt

Add jsonschema support

---

tools/cachito/requirements.txt

We've moved these into the ansible-runner image.

Remove paramiko / ncclient from cachito

---

tools/cachito/requirements.txt

Add ovirt dependencies to cachito

---

tools/cachito/build-requirements.txt
tools/cachito/requirements.txt

Add ansible-pylibssh to cachito

---

.zuul.d/project-templates.yaml
_build/bindep_combined.txt
_build/requirements.yml
tools/requirements.yaml

Add frr.frr collection

---

.zuul.d/project-templates.yaml
_build/bindep_combined.txt
_build/requirements.yml
_build/requirements_combined.txt
tools/requirements.yaml

Add cisco.asa collection

---

.zuul.d/project-templates.yaml
_build/requirements.yml
tools/requirements.yaml

Add ansible.posix collection

---

.zuul.d/project-templates.yaml
_build/requirements.yml
tools/requirements.yaml

Add cloud.common collection

---

.zuul.d/project-templates.yaml
_build/requirements.yml
tools/requirements.yaml

Add servicenow.itsm collection

---

.zuul.d/project-templates.yaml
_build/requirements.yml
tools/requirements.yaml

Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>
Depends-On: https://github.com/ansible/project-config/pull/808

update requirements with ansible.network collection entry

---

_build/requirements_combined.txt

Refresh files

---

tools/cachito/awx-ee/requirements.txt
tools/cachito/awx-ee/setup.cfg

Add awx-ee cachito support

---

.zuul.d/project.yaml

Add irrelevant-files for cachito files

---

tools/cachito/awx-ee/requirements.txt

Depends-On: https://github.com/ansible/network-ee/pull/76

Add pyvmomi to cachito

---

tools/cachito/awx-ee/requirements.txt

Add google.cloud deps for cachito

---

tools/cachito/awx-ee/requirements.txt

Downgrade google-auth

---

tools/execution-environment.yaml

Always use ansible-runner:devel for testing

---

.zuul.d/project-templates.yaml
_build/requirements.yml
tools/requirements.yaml

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

Add kubernetes.core to EE

---

.zuul.d/project-templates.yaml
_build/requirements.yml
tools/requirements.yaml

* amazon.aws
* vmware.vmware_rest
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

Add collections in EE image

---

bindep.txt
tox.ini

Install python38-devel for tox jobs

---

.zuul.d/jobs.yaml
.zuul.d/project.yaml

Fix container-upload jobs

---

playbooks/network-ee-integration-tests/pre.yaml
playbooks/network-ee-integration-tests/run.yaml

Migrate to python38 for integration jobs

---

tests/integration/ansible-navigator.yaml
tests/integration/ansible.cfg

Increase debug logs

---

.zuul.d/project.yaml

Each time we merge changes to a collection, rebuild network-ee images.

Add network-ee post jobs

---

tests/bindep.txt

Use python38-cryptography for test images

---

playbooks/network-ee-integration-tests/pre.yaml
tests/integration/inventories/vyos.yaml

Use /usr/bin/python3.8 for testing

---

playbooks/network-ee-integration-tests/pre.yaml

Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>
This will be used by ansible-network-ee-integration-tests jobs.

Patch collection_name and collection_namespace to inventory

---

playbooks/network-ee-integration-tests/pre.yaml

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1090
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

Don't force Py38 when ansible_connection is ssh

---

tests/integration/inventories/vyos.yaml

Remove explicit localhost in inventory

---

Containerfile
tools/execution-environment.yaml

Remove unused files

---

tests/integration/playbooks/site.yaml

Fail if we don't find any integration targets

---

playbooks/network-ee-build-container-image-base/pre.yaml

This is our first attempt to help cut down on timeout issues we still
with quay.io.

Pre pull some builder images

---

.zuul.d/integration-jobs.yaml
.zuul.d/jobs.yaml
.zuul.d/project.yaml

Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>
Depends-On: https://github.com/ansible/ansible-runner/pull/856

Enable stable-2.12

---

.zuul.d/integration-jobs.yaml

Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1142

Add network-ee-integration-tests-stable-2.12

---

tests/integration/inventories/nxos.yaml

Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>

Add inventory file for nxos
